export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const QUANTITY_UP = 'QUANTITY_UP';
export const QUANTITY_DOWN = 'QUANTITY_DOWN';
export const SHOW_CART = 'SHOW_CART';
export const SUBTRACT_QUANTITY = 'SUBTRACT_QUANTITY';
export const SHOW_PRODUCT = 'SHOW_PRODUCT'
export const LIST_PRODUCTS = 'LIST_PRODUCTS'